### ISSUE TITLE
error: ‘FDFSHTTPParams {aka struct <anonymous>}’ has no member named ‘support_multi_range’

### ISSUE THREAD

**Issue by StupidStudentInSchool** [happyfish100/fastdfs-nginx-module#39]
/home/user/fastDFS/fastdfs-nginx-module/src//common.c:597:16: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘int’ [-Wformat=]
                "%"PRIx64, get_current_time_us());
                ^~~        ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fastcommon/common_define.h:31:0,
                 from /usr/include/fastcommon/logger.h:15,
                 from /home/user/fastDFS/fastdfs-nginx-module/src//common.c:21,
                 from /home/user/fastDFS/fastdfs-nginx-module/src//ngx_http_fastdfs_module.c:6:
/usr/include/inttypes.h:121:34: note: format string is defined here
 # define PRIx64  __PRI64_PREFIX "x"
In file included from /home/user/fastDFS/fastdfs-nginx-module/src//ngx_http_fastdfs_module.c:6:0:
/home/user/fastDFS/fastdfs-nginx-module/src//common.c: In function ‘fdfs_http_request_handler’:
/home/user/fastDFS/fastdfs-nginx-module/src//common.c:1245:61: **error: ‘FDFSHTTPParams {aka struct <anonymous>}’ has no member named ‘support_multi_range’**
                 (pContext->range_count > 1 && !g_http_params.support_multi_range))
                                                             ^
objs/Makefile:1171: recipe for target 'objs/addon/src/ngx_http_fastdfs_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_fastdfs_module.o] Error 1
make[1]: Leaving directory '/home/user/fastDFS/nginx-1.12.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

下面是fastdfs-nginx-module/src/config文件

ngx_addon_name=ngx_http_fastdfs_module

if test -n "${ngx_module_link}"; then
    ngx_module_type=HTTP
    ngx_module_name=$ngx_addon_name
    ngx_module_incs="/usr/include/fastdfs /usr/include/fastcommon/"
    ngx_module_libs="-lfastcommon -lfdfsclient"
    ngx_module_srcs="$ngx_addon_dir/ngx_http_fastdfs_module.c"
    ngx_module_deps=
    CFLAGS="$CFLAGS -D_FILE_OFFSET_BITS=64 -DFDFS_OUTPUT_CHUNK_SIZE='256*1024' -DFDFS_MOD_CONF_FILENAME='\"/etc/fdfs/mod_fastdfs.conf\"'"
    . auto/module
else
    HTTP_MODULES="$HTTP_MODULES ngx_http_fastdfs_module"
    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_fastdfs_module.c"
    CORE_INCS="$CORE_INCS /usr/include/fastdfs /usr/include/fastcommon/"
    CORE_LIBS="$CORE_LIBS -L/usr/lib -lfastcommon -lfdfsclient"
    CFLAGS="$CFLAGS -D_FILE_OFFSET_BITS=64 -DFDFS_OUTPUT_CHUNK_SIZE='256*1024' -DFDFS_MOD_CONF_FILENAME='\"/etc/fdfs/mod_fastdfs.conf\"'"
fi
~            

这是什么问题，怎么解决

**Comment by yushifu** [comment]
you should download the newest fastdfs ,then install it ,the problem will dispear
