### ISSUE TITLE
make时候出错 要求把 . 换成 ->

### ISSUE THREAD

**Issue by AngleBeats147753** [happyfish100/fastdfs-nginx-module#50]
错误：
/usr/local/nginx/fastdfs-nginx-module/src/common.c: In function ‘fdfs_mod_init’:
/usr/local/nginx/fastdfs-nginx-module/src/common.c:387:22: error: request for member ‘count’ in something not a structure or union
   g_storage_ids_by_id.count, g_storage_ids_by_ip.count,
                      ^
/usr/local/nginx/fastdfs-nginx-module/src/common.c:387:49: error: ‘g_storage_ids_by_ip’ is a pointer; did you mean to use ‘->’?
   g_storage_ids_by_id.count, g_storage_ids_by_ip.count,
                                                 ^
                                                 ->
环境：
gcc-8 / gcc-7 （都试过了，还是不行）
nginx-1.15.4 / ngin-1.13.7

**Comment by AngleBeats147753** [comment]
补充一下环境：
Linux raspberrypi 4.19.57-v7l+
fastdfs-nginx-module 1.21
libfastcommon 1.41

**Comment by happyfish100** [comment]
INSTALL文件做了说明，对fastdfs的版本要求是v6.0及以上版本。我贴下：
#step 1. first install the FastDFS storage server and client library,
         the FastDFS version should >= 6.0.0. download with git:
         git clone https://github.com/happyfish100/fastdfs

**Comment by AngleBeats147753** [comment]
十分感谢，才看见昨天更新了
