### ISSUE TITLE
/usr/include/fastdfs/fdfs_define.h:15:27: fatal error: common_define.h: No such file or directory

### ISSUE THREAD

**Issue by lgd8069465** [happyfish100/fastdfs-nginx-module#51]
/usr/include/fastdfs/fdfs_define.h:15:27: fatal error: common_define.h: No such file or directory
libfastcommon-1.0.39
fastdfs-5.11
fastdfs-nginx-module-1.20
nginx-1.16.1/nginx-1.17.4  
why?

**Comment by happyfish100** [comment]
you should make and install libfastcommon  and FastDFS client first.

**Comment by lgd8069465** [comment]
I sure i already installed libfastcommon and FastDFS,and fix with this document https://github.com/happyfish100/fastdfs-nginx-module/issues/31 ,thanks anyway@happyfish100 and @xunchong99
