### ISSUE TITLE
macos 编译报错 fatal error: 'fastdfs/fdfs_define.h' file not found

### ISSUE THREAD

**Issue by Shj451148969** [happyfish100/fastdfs-nginx-module#53]
In file included from /Users/shuhongji/Documents/fastdfs/fastdfs-nginx-module-1.20/src/ngx_http_fastdfs_module.c:6:
/Users/shuhongji/Documents/fastdfs/fastdfs-nginx-module-1.20/src/common.c:26:10: fatal error: 'fastdfs/fdfs_define.h' file not found
#include "fastdfs/fdfs_define.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [objs/addon/src/ngx_http_fastdfs_module.o] Error 1
make: *** [build] Error 2

**Comment by Shj451148969** [comment]
版本
libfastcommon-1.0.41
fastdfs-6.01
nginx-1.17.5
fastdfs-nginx-module-1.21

**Comment by Shj451148969** [comment]
使用软连接后此问题解决，但是出现了新的问题
ld: library not found for -lfdfsclient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [objs/nginx] Error 1
make: *** [build] Error 2

**Comment by happyfish100** [comment]
没有找到 libfdfsclient.so，确认下在 /usr/lib 或者  /usr/local/lib 下是否存在。
可以使用检测命令如下：
ls -l  /usr/lib/libfdfsclient.so  /usr/local/lib/libfdfsclient.so

**Comment by Shj451148969** [comment]
问题解决了，确保 /usr/local/include 目录下有fastcommon和fastdfs目录存在就行了，可以使用ln -sv来解决
