### ISSUE TITLE
/fastdfs-nginx-module/src//common.c: In function 'fdfs_mod_init'

### ISSUE THREAD

**Issue by JosenChina** [happyfish100/fastdfs-nginx-module#84]
I had take this error 
`cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -D_FILE_OFFSET_BITS=64 -DFDFS_OUTPUT_CHUNK_SIZE='256*1024' -DFDFS_MOD_CONF_FILENAME='"/etc/fdfs/mod_fastdfs.conf"'  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /usr/local/include -I src/stream \
        -o objs/addon/src/ngx_http_fastdfs_module.o \
        ../fastdfs-nginx-module/src//ngx_http_fastdfs_module.c
In file included from ../fastdfs-nginx-module/src//ngx_http_fastdfs_module.c:6:0:
../fastdfs-nginx-module/src//common.c: In function 'fdfs_mod_init':
../fastdfs-nginx-module/src//common.c:351:32: error: request for member 'path' in something not a structure or union
     g_fdfs_store_paths.paths[i].path);
                                ^
../fastdfs-nginx-module/src//common.c:387:22: error: request for member 'count' in something not a structure or union
   g_storage_ids_by_id.count, g_storage_ids_by_ip.count,
                      ^
../fastdfs-nginx-module/src//common.c:387:49: error: 'g_storage_ids_by_ip' is a pointer; did you mean to use '->'?
   g_storage_ids_by_id.count, g_storage_ids_by_ip.count,
                                                 ^
                                                 ->
../fastdfs-nginx-module/src//common.c:401:47: error: request for member 'path' in something not a structure or union
      group_store_paths[k].store_paths.paths[i].path);
                                               ^
../fastdfs-nginx-module/src//common.c: In function 'fdfs_http_request_handler':
../fastdfs-nginx-module/src//common.c:1088:42: error: request for member 'path' in something not a structure or union
      pStorePaths->paths[store_path_index].path, \
                                          ^
../fastdfs-nginx-module/src//common.c:1433:41: error: request for member 'path' in something not a structure or union
     pStorePaths->paths[store_path_index].path, \
                                         ^
make[1]: *** [objs/Makefile:1369: objs/addon/src/ngx_http_fastdfs_module.o] Error 1
make[1]: Leaving directory '/nginx_package/nginx'
make: *** [Makefile:8: build] Error 2`

I "make" the code in docker container of alpine linux, and my nginx version is 1.16(or 1.18), i never success , why ?

**Comment by adalaohu** [comment]
the same with you...

**Comment by QIXQI** [comment]
解决了吗？

**Comment by 674019130** [comment]
Hi, did you resolve this?

**Comment by happyfish100** [comment]
需要先编译和安装 fastdfs client library。
