### ISSUE TITLE
The install nginx error!

### ISSUE THREAD

**Issue by codeWang-J** [happyfish100/fastdfs-nginx-module#90]
/fastdfs-nginx-module-1.20/src/common.c:902:42: error: ‘%s’ directive output may be truncated writing up to 510 bytes into a region of size between 111 and 127 [-Werror=format-truncation=]
  901 |   file_id_without_group = uri + 1; //skip /
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
  902 |   snprintf(file_id, sizeof(file_id), "%s/%s", \
      |                                          ^~
In file included from /usr/include/stdio.h:866,
                 from src/os/unix/ngx_linux_config.h:23,
                 from src/core/ngx_config.h:26,
                 from /home/wj/fastdfs-nginx-module-1.20/src/ngx_http_fastdfs_module.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 2 and 528 bytes into a destination of size 128
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |        __glibc_objsize (__s), __fmt,
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |        __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~
In file included from /home/wj/fastdfs-nginx-module-1.20/src/ngx_http_fastdfs_module.c:6:
/home/wj/fastdfs-nginx-module-1.20/src/common.c:856:39: error: ‘%s’ directive output may be truncated writing up to 510 bytes into a region of size 128 [-Werror=format-truncation=]
  856 |   snprintf(file_id, sizeof(file_id), "%s", uri + 1);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /usr/include/stdio.h:866,
                 from src/os/unix/ngx_linux_config.h:23,
                 from src/core/ngx_config.h:26,
                 from /home/wj/fastdfs-nginx-module-1.20/src/ngx_http_fastdfs_module.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin_snprintf’ output between 1 and 511 bytes into a destination of size 128
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |        __glibc_objsize (__s), __fmt,
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |        __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1207：objs/addon/src/ngx_http_fastdfs_module.o] 错误 1
make[1]: 离开目录“/home/wj/nginx-1.15.2”
make: *** [Makefile:8：build] 错误 2

**Comment by happyfish100** [comment]
烦请告知操作系统和gcc的版本号

**Comment by loriensinsight** [comment]
> 烦请告知操作系统和gcc的版本号

我有同样的报错
操作系统是Debian GNU/Linux 11 (bullseye) （在win10或win server2016下wmware起的虚拟机）
gcc的版本是gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
fdfs版本6.0.7
libfastcommon版本1.0.55
fastdfs-nginx-module版本1.22
nginx 1.15.1、1.18.0、1.21.5均是同样报错

**Comment by happyfish100** [comment]
感谢反馈，问题已修复，使用 master分支即可。
对于大于等于7.0的gcc，需要在CFLAGS中增加选项：-Wformat-truncation=0 -Wformat-overflow=0
