### ISSUE TITLE
nginx 编译通过后运行提示以下报错

### ISSUE THREAD

**Issue by Duanlegs** [happyfish100/fastdfs-nginx-module#93]
symbol lookup error: nginx: master process /usr/local/nginx-1.20.2/sbin/nginx: undefined symbol: iniGetIntValue

**Comment by happyfish100** [comment]
libfastcommon版本问题，编译和运行的版本需要保持一致

**Comment by coderjbin** [comment]
nginx: symbol lookup error: nginx: undefined symbol: g_fdfs_base_path，请问这个是怎么回事呢

**Comment by happyfish100** [comment]
FDFS client library编译和运行要一致。
如果 /usr/local/lib 下有  libfastcommon.so 和 libfdfsclient.so，需要手工删除掉，命令行如下：
sudo rm -f /usr/local/lib/libfastcommon.so /usr/local/lib/libfdfsclient.so
