### ISSUE TITLE
关于make 失败问题

### ISSUE THREAD

**Issue by fsfsfsfsfs9** [happyfish100/fastdfs-nginx-module#98]
报错内容：/usr/local/package/fastdfs-nginx-module-1.20/src//common.c:1245:61: 错误：‘FDFSHTTPParams’没有名为‘support_multi_range’的成员
系统centos7
nginx-1.16.1
fastdfs-nginx-module-1.20

**Comment by fsfsfsfsfs9** [comment]
fastDfs5.08  -> fastdfs-nginx-module-1.19

**Comment by happyfish100** [comment]
建议都使用最新版本。
